# SPDX-License-Identifier: GPL-2.0-only
dtb-$(CONFIG_ARCH_STM32) += \
	stm32mp257f-dk.dtb \
	stm32mp257f-ev1.dtb

ifeq ($(CONFIG_STM32MP25_REVA), y)
	dtb-$(CONFIG_ARCH_STM32) += \
		stm32mp257f-ev-revB.dtb
endif
