# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_STM32) += \
	ccmp133-dvk.dtb \
	ccmp133-mfg-functional.dtb \
	ccmp133-mfg-functional-wb.dtb \
	ccmp157-dvk.dtb \
	ccmp157-mfg-functional.dtb \
	ccmp157-mfg-functional-wb.dtb \
	_ov_board_mikroe-accel2-click_ccmp13-dvk.dtbo \
	_ov_board_mikroe-accel2-click_ccmp15-dvk.dtbo \
	_ov_board_mikroe-gyro-click_ccmp13-dvk.dtbo \
	_ov_board_mikroe-gyro-click_ccmp15-dvk.dtbo \
	_ov_board_mikroe-i2c-to-spi-click_ccmp13-dvk.dtbo \
	_ov_board_mikroe-i2c-to-spi-click_ccmp15-dvk.dtbo \
	_ov_board_nhd-3-5-640480ef-msxp-mipi-dsi_ccmp15-dvk.dtbo \
	_ov_board_can1_ccmp15-dvk.dtbo \
	_ov_board_can2_ccmp15-dvk.dtbo \
	_ov_board_dlc0200ccp04df-mipi-dsi_ccmp15-dvk.dtbo \
	_ov_board_eth0-10-100_ccmp15-dvk.dtbo \
	_ov_board_fusion10-lvds_ccmp15-dvk.dtbo \
	_ov_board_fusion7-parallel_ccmp15-dvk.dtbo \
	_ov_board_g101evn010-lvds_ccmp15-dvk.dtbo \
	_ov_board_sv4e-mipi-analyzer_ccmp15-dvk.dtbo \
	_ov_board_pwm8_ccmp13-dvk.dtbo \
	_ov_board_v1_ccmp15-dvk.dtbo \
	_ov_board_v2_ccmp13-dvk.dtbo \
	_ov_board_v2_ccmp15-dvk.dtbo \
	_ov_som_bt_ccmp13.dtbo \
	_ov_som_bt_ccmp15.dtbo \
	_ov_som_bt_test_ccmp13.dtbo \
	_ov_som_bt_test_ccmp15.dtbo \
	_ov_som_v1_ccmp15.dtbo \
	_ov_som_wifi_ccmp13.dtbo \
	_ov_som_wifi_ccmp15.dtbo
