# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_SOC_IMX6Q) += \
	imx6dl-ccimx6sbc.dtb \
	imx6dl-ccimx6sbc-id131.dtb \
	imx6dl-ccimx6sbc-w.dtb \
	imx6dl-ccimx6sbc-wb.dtb \
	imx6q-ccimx6sbc.dtb \
	imx6q-ccimx6sbc-id129.dtb \
	imx6q-ccimx6sbc-id130.dtb \
	imx6q-ccimx6sbc-w.dtb \
	imx6q-ccimx6sbc-wb.dtb \
	imx6q-ccimx6sbc-wb-ldo-bypass.dtb \
	imx6qp-ccimx6qp-mfg.dtb \
	imx6qp-ccimx6qp-mfg-rf.dtb \
	imx6qp-ccimx6qpsbc.dtb \
	imx6qp-ccimx6qpsbc-id160.dtb \
	imx6qp-ccimx6qpsbc-wb.dtb
dtb-$(CONFIG_SOC_IMX6UL) += \
	imx6ul-ccimx6ul-mfg.dtb \
	imx6ul-ccimx6ul-mfg-rf.dtb \
	imx6ul-ccimx6ulsbc.dtb \
	imx6ul-ccimx6ulsbc-id135.dtb \
	imx6ul-ccimx6ulsbc-id136.dtb \
	imx6ul-ccimx6ulsbc-wb.dtb \
	imx6ul-ccimx6ulsbc-wb-mfg.dtb \
	imx6ul-ccimx6ulstarter.dtb \
	imx6ul-ccimx6ulstarter-id129.dtb \
	imx6ul-ccimx6ulstarter-wb.dtb \
	imx6ul-ccimx6ulstarter-wb-mfg.dtb
