# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_STM32) += \
	ccmp13_bt_test.dtbo \
	ccmp13_bt.dtbo \
	ccmp13_wifi.dtbo \
	ccmp13-dvk_mikroe-accel2-click.dtbo \
	ccmp13-dvk_mikroe-gyro-click.dtbo \
	ccmp13-dvk_mikroe-i2c-to-spi-click.dtbo \
	ccmp13-dvk_pwm8.dtbo \
	ccmp13-dvk_v2.dtbo \
	ccmp13-dvk_v3.dtbo \
	ccmp133-dvk.dtb \
	ccmp133-mfg-functional-wb.dtb \
	ccmp133-mfg-functional.dtb \
	ccmp15_bt_test.dtbo \
	ccmp15_bt.dtbo \
	ccmp15_v1.dtbo \
	ccmp15_wifi.dtbo \
	ccmp15-dvk_can1.dtbo \
	ccmp15-dvk_can2.dtbo \
	ccmp15-dvk_dlc0200ccp04df-mipi-dsi.dtbo \
	ccmp15-dvk_eth0-10-100.dtbo \
	ccmp15-dvk_fusion10-lvds.dtbo \
	ccmp15-dvk_fusion7-parallel.dtbo \
	ccmp15-dvk_g101evn010-lvds.dtbo \
	ccmp15-dvk_mikroe-accel2-click.dtbo \
	ccmp15-dvk_mikroe-gyro-click.dtbo \
	ccmp15-dvk_mikroe-i2c-to-spi-click.dtbo \
	ccmp15-dvk_nhd-3-5-640480ef-msxp-mipi-dsi.dtbo \
	ccmp15-dvk_sv4e-mipi-analyzer.dtbo \
	ccmp15-dvk_v1.dtbo \
	ccmp15-dvk_v2.dtbo \
	ccmp157-dvk.dtb \
	ccmp157-mfg-functional-wb.dtb \
	ccmp157-mfg-functional.dtb
