dtb-$(CONFIG_ARCH_FSL_IMX8QXP) += ccimx8x-sbc-express-id129.dtb \
				  ccimx8x-sbc-express-wb.dtb \
				  ccimx8x-sbc-express-wb-mfg.dtb \
				  ccimx8x-sbc-express.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
