# SPDX-License-Identifier: GPL-2.0-only

ccmp25-dtbs :=		ccmp25-dvk.dtb \
			ccmp25-dvk_e55rb-i-mw346-c-mipi-dsi.dtbo \
			ccmp25-dvk_g101evn010-lvds.dtbo \
			ccmp25-dvk_ov5640-mipi-csi.dtbo \
			ccmp25-dvk_mikroe-accel2-click.dtbo \
			ccmp25-dvk_mikroe-gyro-click.dtbo \
			ccmp25-dvk_mikroe-i2c-to-spi-click.dtbo \
			ccmp25-dvk_mikroe-mcp2518fd-click.dtbo \
			ccmp25-dvk_n25q256a-spi-nor-flash.dtbo \
			ccmp25-dvk_nhd-3-5-640480ef-msxp-mipi-dsi.dtbo \
			ccmp25-dvk_usb-3-0-typec.dtbo \
			ccmp25_bt.dtbo \
			ccmp25_wifi.dtbo

dtb-$(CONFIG_ARCH_STM32) += \
	ccmp25.dtb \
	ccmp25-mfg-functional.dtb \
	ccmp25-mfg-functional-wb.dtb
