dtb-$(CONFIG_ARCH_FSL_IMX8QXP) += ccimx8dx-sbc-pro-wb.dtb \
				  ccimx8dx-sbc-pro.dtb \
				  ccimx8qxp-sbc-express-id129.dtb \
				  ccimx8qxp-sbc-express-wb.dtb \
				  ccimx8qxp-sbc-express.dtb \
				  ccimx8qxp-sbc-pro-id135.dtb \
				  ccimx8qxp-sbc-pro-wb.dtb \
				  ccimx8qxp-sbc-pro.dtb \

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
