/* SPDX-License-Identifier: (GPL-2.0-only OR BSD-3-Clause) */
/*
 * Copyright (C) 2024, STMicroelectronics - All Rights Reserved
 */

#ifndef __DT_BINDINGS_REGULATOR_STM32MP21_REGULATOR_H
#define __DT_BINDINGS_REGULATOR_STM32MP21_REGULATOR_H

/* SCMI voltage domains identifiers */

/* SOC Internal regulators */
#define VOLTD_SCMI_VDDIO1		0
#define VOLTD_SCMI_VDDIO2		1
#define VOLTD_SCMI_VDDIO3		2
#define VOLTD_SCMI_ADC			3
#define VOLTD_SCMI_VREFBUF		4

/* STPMIC regulators (STPMIC25/STM32MP2L/STPMIC1L) */
#define VOLTD_SCMI_STPMIC_BUCK1		5
#define VOLTD_SCMI_STPMIC_BUCK2		6
#define VOLTD_SCMI_STPMIC_BUCK3		7
#define VOLTD_SCMI_STPMIC_BUCK4		8
#define VOLTD_SCMI_STPMIC_BUCK5		9
#define VOLTD_SCMI_STPMIC_BUCK6		10
#define VOLTD_SCMI_STPMIC_BUCK7		11
#define VOLTD_SCMI_STPMIC_LDO1		12
#define VOLTD_SCMI_STPMIC_LDO2		13
#define VOLTD_SCMI_STPMIC_LDO3		14
#define VOLTD_SCMI_STPMIC_LDO4		15
#define VOLTD_SCMI_STPMIC_LDO5		16
#define VOLTD_SCMI_STPMIC_LDO6		17
#define VOLTD_SCMI_STPMIC_LDO7		18
#define VOLTD_SCMI_STPMIC_LDO8		19
#define VOLTD_SCMI_STPMIC_REFDDR	20
#define VOLTD_SCMI_STPMIC_GPO1		21
#define VOLTD_SCMI_STPMIC_GPO2		22
#define VOLTD_SCMI_STPMIC_GPO3		23
#define VOLTD_SCMI_STPMIC_GPO4		24
#define VOLTD_SCMI_STPMIC_GPO5		25

/* External regulators */
#define VOLTD_SCMI_REGU0		26
#define VOLTD_SCMI_REGU1		27
#define VOLTD_SCMI_REGU2		28
#define VOLTD_SCMI_REGU3		29
#define VOLTD_SCMI_REGU4		30

#endif /*__DT_BINDINGS_REGULATOR_STM32MP21_REGULATOR_H */
